# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testApp

  target 'testAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end
inhibit_all_warnings!

pod 'AMapSearch'
pod 'VKVideoPlayer'
pod 'Masonry'
pod 'PinYin4Objc'
pod 'DateTools'
end
